// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

namespace ParkApi.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    partial class ParkApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkType")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Montana",
                            Name = "Glacier National Park",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "California",
                            Name = "Death Valley National Park",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "Washington",
                            Name = "Olympic National Park",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "Washington",
                            Name = "North Cascades National Park",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Location = "California",
                            Name = "Sequoia National Park",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 6,
                            Location = "Oregon",
                            Name = "Milo McIver State Park",
                            ParkType = "State"
                        },
                        new
                        {
                            ParkId = 7,
                            Location = "Oregon",
                            Name = "Silver Falls Park",
                            ParkType = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
